version: '3.8'

services:
  backend:
    build:
      context: ./API/api
    ports:
      - "8080:8080"
    networks:
      - tp_network
    depends_on:
     - mongodb
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://admin:admin123@mongodb:27017/base_de_datos?authSource=admin

  bot:
    build:
      context: ./BOT/Bot
    ports:
      - "8081:8081"
    networks:
      - tp_network
    depends_on:
     - backend

  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin123
    volumes:
      - mongodb_data:/data/db
    networks:
     - tp_network 

networks:
  tp_network:
    driver: bridge

volumes:
  mongodb_data:
