/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package gui.views;

import com.formdev.flatlaf.intellijthemes.materialthemeuilite.FlatMaterialLighterIJTheme;
import gui.PrincipalMenu;
import java.awt.Color;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import logic.LogicController;
import logic.User;
public class ProfilePanel extends javax.swing.JPanel {

    User currentUser;
    LogicController logicController;
    PrincipalMenu principalMenu;
    public ProfilePanel(LogicController logicController, User user, PrincipalMenu principalMenu) {
        initComponents();
        FlatMaterialLighterIJTheme.setup();
        this.logicController = logicController;
        this.principalMenu = principalMenu;
        this.currentUser = user;
        restartDeleteUser();
        restartChangePassword();
        ImageIcon originalIcon = new javax.swing.ImageIcon(this.getClass().getResource("/icons/LogoNoText.png"));
        Image image = originalIcon.getImage().getScaledInstance(170,170,Image.SCALE_SMOOTH);
        ImageIcon scaledIcon = new javax.swing.ImageIcon(image);
        logoLalbel.setIcon(scaledIcon);
        username.setText(user.getUsername());
        
        if(currentUser.existImage()){
            ImageIcon profilePicture = new ImageIcon(currentUser.getImage());
            Image profileImage = profilePicture.getImage().getScaledInstance(200,200,Image.SCALE_SMOOTH);
            ImageIcon scaledProfilePicture = new ImageIcon(profileImage);
            pictureLabel.setIcon(scaledProfilePicture);
        }
        else{
            ImageIcon defaultPicture = new ImageIcon(this.getClass().getResource("/icons/default_avatar.png"));
            Image defaultImage = defaultPicture.getImage().getScaledInstance(200,200,Image.SCALE_SMOOTH);
            ImageIcon scaledDefaultPicture = new ImageIcon(defaultImage);
            pictureLabel.setIcon(scaledDefaultPicture);
        }
        
        jPanel1.revalidate();
        jPanel1.repaint();
    }
    
    private void restartDeleteUser(){
        PasswordField.setText("********");
        PasswordField.setForeground(new Color(204,204,204));
        repeatPasswordField.setText("********");
        repeatPasswordField.setForeground(new Color(204,204,204));
        passwordNotMatch.setVisible(false);
        fieldsEmpty.setVisible(false);
        deleteBtn.setVisible(false);
        cancelBtn.setVisible(false);
        repeatSeparator.setVisible(false);
        PasswordLabel.setVisible(false);
        PasswordField.setVisible(false);
        passwordSeparator.setVisible(false);
        repeatPasswordField.setVisible(false);
        repeatPasswordLabel.setVisible(false);
        wrongPassword.setVisible(false);
        
    }
    
    private void restartChangePassword(){
        actualPasswordField.setText("********");
        actualPasswordField.setForeground(new Color(204,204,204));
        newPasswordField.setText("********");
        newPasswordField.setForeground(new Color(204,204,204));
        newRepeatField.setText("********");
        newRepeatField.setForeground(new Color(204,204,204));
        actualPasswordField.setVisible(false);
        actualPasswordLabel.setVisible(false);
        actualPasswordSeparator.setVisible(false);
        newPasswordField.setVisible(false);
        newPasswordLabel.setVisible(false);
        newPasswordSeparator.setVisible(false);
        newRepeatField.setVisible(false);
        newRepeatLabel.setVisible(false);
        newRepeatSeparator.setVisible(false);
        changeBtn.setVisible(false);
        cancelChangeBtn.setVisible(false);
        changeFieldsEmpty.setVisible(false);
        changeWrongPassword.setVisible(false);
        changePasswordNotMatch.setVisible(false);
        changeSucces.setVisible(false);
    }
    private void restartChangePasswordWithoutLabels(){
        actualPasswordField.setText("********");
        actualPasswordField.setForeground(new Color(204,204,204));
        newPasswordField.setText("********");
        newPasswordField.setForeground(new Color(204,204,204));
        newRepeatField.setText("********");
        newRepeatField.setForeground(new Color(204,204,204));
        changeFieldsEmpty.setVisible(false);
        changeWrongPassword.setVisible(false);
        changePasswordNotMatch.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        pictureLabel = new javax.swing.JLabel();
        username = new javax.swing.JLabel();
        logoLalbel = new javax.swing.JLabel();
        fieldsEmpty = new javax.swing.JLabel();
        passwordNotMatch = new javax.swing.JLabel();
        profilePictureBtn = new javax.swing.JButton();
        repeatPasswordLabel = new javax.swing.JLabel();
        repeatPasswordField = new javax.swing.JPasswordField();
        passwordSeparator = new javax.swing.JSeparator();
        deleteUserBtn = new javax.swing.JButton();
        PasswordLabel = new javax.swing.JLabel();
        PasswordField = new javax.swing.JPasswordField();
        repeatSeparator = new javax.swing.JSeparator();
        deleteBtn = new javax.swing.JButton();
        cancelBtn = new javax.swing.JButton();
        changePasswordBtn = new javax.swing.JButton();
        actualPasswordLabel = new javax.swing.JLabel();
        actualPasswordField = new javax.swing.JPasswordField();
        actualPasswordSeparator = new javax.swing.JSeparator();
        newPasswordLabel = new javax.swing.JLabel();
        newPasswordField = new javax.swing.JPasswordField();
        newPasswordSeparator = new javax.swing.JSeparator();
        newRepeatLabel = new javax.swing.JLabel();
        newRepeatField = new javax.swing.JPasswordField();
        newRepeatSeparator = new javax.swing.JSeparator();
        changeBtn = new javax.swing.JButton();
        cancelChangeBtn = new javax.swing.JButton();
        changeFieldsEmpty = new javax.swing.JLabel();
        changePasswordNotMatch = new javax.swing.JLabel();
        changeWrongPassword = new javax.swing.JLabel();
        wrongPassword = new javax.swing.JLabel();
        changeSucces = new javax.swing.JLabel();

        jPanel1.setBackground(new java.awt.Color(236, 236, 236));

        pictureLabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        username.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        username.setForeground(new java.awt.Color(0, 0, 0));
        username.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        username.setText("Username");

        logoLalbel.setIcon(new javax.swing.ImageIcon("D:\\Laboral\\Practicas Java\\ToDoListGraphic\\src\\main\\java\\gui\\LogoNoText.png")); // NOI18N

        fieldsEmpty.setBackground(new java.awt.Color(255, 255, 255));
        fieldsEmpty.setForeground(new java.awt.Color(255, 0, 51));
        fieldsEmpty.setText("Complete todos los campos");

        passwordNotMatch.setBackground(new java.awt.Color(255, 255, 255));
        passwordNotMatch.setForeground(new java.awt.Color(255, 0, 51));
        passwordNotMatch.setText("Las contraseñas no concuerdan");

        profilePictureBtn.setBackground(new java.awt.Color(51, 51, 51));
        profilePictureBtn.setFont(new java.awt.Font("Rockwell", 0, 14)); // NOI18N
        profilePictureBtn.setForeground(new java.awt.Color(255, 255, 255));
        profilePictureBtn.setText("Cambiar foto de Perfil");
        profilePictureBtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        profilePictureBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        profilePictureBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                profilePictureBtnMouseClicked(evt);
            }
        });

        repeatPasswordLabel.setBackground(new java.awt.Color(255, 255, 255));
        repeatPasswordLabel.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        repeatPasswordLabel.setForeground(new java.awt.Color(0, 0, 0));
        repeatPasswordLabel.setText("Ingrese nuevamente la contraseña");

        repeatPasswordField.setBackground(new java.awt.Color(236, 236, 236));
        repeatPasswordField.setForeground(new java.awt.Color(204, 204, 204));
        repeatPasswordField.setText("********");
        repeatPasswordField.setBorder(null);
        repeatPasswordField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                repeatPasswordFieldMousePressed(evt);
            }
        });

        deleteUserBtn.setBackground(new java.awt.Color(51, 51, 51));
        deleteUserBtn.setFont(new java.awt.Font("Rockwell", 0, 14)); // NOI18N
        deleteUserBtn.setForeground(new java.awt.Color(255, 255, 255));
        deleteUserBtn.setText("Borrar Usuario");
        deleteUserBtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        deleteUserBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        deleteUserBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                deleteUserBtnMouseClicked(evt);
            }
        });

        PasswordLabel.setBackground(new java.awt.Color(255, 255, 255));
        PasswordLabel.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        PasswordLabel.setForeground(new java.awt.Color(0, 0, 0));
        PasswordLabel.setText("Ingrese su contraseña");

        PasswordField.setBackground(new java.awt.Color(236, 236, 236));
        PasswordField.setForeground(new java.awt.Color(204, 204, 204));
        PasswordField.setText("********");
        PasswordField.setBorder(null);
        PasswordField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                PasswordFieldMousePressed(evt);
            }
        });

        deleteBtn.setBackground(new java.awt.Color(51, 51, 51));
        deleteBtn.setFont(new java.awt.Font("Rockwell", 0, 12)); // NOI18N
        deleteBtn.setForeground(new java.awt.Color(255, 0, 0));
        deleteBtn.setText("Borrar");
        deleteBtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        deleteBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        deleteBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                deleteBtnMouseClicked(evt);
            }
        });
        deleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBtnActionPerformed(evt);
            }
        });

        cancelBtn.setBackground(new java.awt.Color(51, 51, 51));
        cancelBtn.setFont(new java.awt.Font("Rockwell", 0, 12)); // NOI18N
        cancelBtn.setForeground(new java.awt.Color(255, 255, 255));
        cancelBtn.setText("Cancelar");
        cancelBtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        cancelBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cancelBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cancelBtnMouseClicked(evt);
            }
        });

        changePasswordBtn.setBackground(new java.awt.Color(51, 51, 51));
        changePasswordBtn.setFont(new java.awt.Font("Rockwell", 0, 14)); // NOI18N
        changePasswordBtn.setForeground(new java.awt.Color(255, 255, 255));
        changePasswordBtn.setText("Cambiar contraseña");
        changePasswordBtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        changePasswordBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        changePasswordBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                changePasswordBtnMouseClicked(evt);
            }
        });

        actualPasswordLabel.setBackground(new java.awt.Color(255, 255, 255));
        actualPasswordLabel.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        actualPasswordLabel.setForeground(new java.awt.Color(0, 0, 0));
        actualPasswordLabel.setText("Ingrese su contraseña");

        actualPasswordField.setBackground(new java.awt.Color(236, 236, 236));
        actualPasswordField.setForeground(new java.awt.Color(204, 204, 204));
        actualPasswordField.setText("********");
        actualPasswordField.setBorder(null);
        actualPasswordField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                actualPasswordFieldMousePressed(evt);
            }
        });

        newPasswordLabel.setBackground(new java.awt.Color(255, 255, 255));
        newPasswordLabel.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        newPasswordLabel.setForeground(new java.awt.Color(0, 0, 0));
        newPasswordLabel.setText("Ingrese su nueva contraseña");

        newPasswordField.setBackground(new java.awt.Color(236, 236, 236));
        newPasswordField.setForeground(new java.awt.Color(204, 204, 204));
        newPasswordField.setText("********");
        newPasswordField.setBorder(null);
        newPasswordField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                newPasswordFieldMousePressed(evt);
            }
        });

        newRepeatLabel.setBackground(new java.awt.Color(255, 255, 255));
        newRepeatLabel.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        newRepeatLabel.setForeground(new java.awt.Color(0, 0, 0));
        newRepeatLabel.setText("Ingrese nuevamente su nueva contraseña");

        newRepeatField.setBackground(new java.awt.Color(236, 236, 236));
        newRepeatField.setForeground(new java.awt.Color(204, 204, 204));
        newRepeatField.setText("********");
        newRepeatField.setBorder(null);
        newRepeatField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                newRepeatFieldMousePressed(evt);
            }
        });

        changeBtn.setBackground(new java.awt.Color(51, 51, 51));
        changeBtn.setFont(new java.awt.Font("Rockwell", 0, 12)); // NOI18N
        changeBtn.setForeground(new java.awt.Color(255, 255, 255));
        changeBtn.setText("Cambiar");
        changeBtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        changeBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        changeBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                changeBtnMouseClicked(evt);
            }
        });
        changeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changeBtnActionPerformed(evt);
            }
        });

        cancelChangeBtn.setBackground(new java.awt.Color(51, 51, 51));
        cancelChangeBtn.setFont(new java.awt.Font("Rockwell", 0, 12)); // NOI18N
        cancelChangeBtn.setForeground(new java.awt.Color(255, 255, 255));
        cancelChangeBtn.setText("Cancelar");
        cancelChangeBtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        cancelChangeBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cancelChangeBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cancelChangeBtnMouseClicked(evt);
            }
        });

        changeFieldsEmpty.setBackground(new java.awt.Color(255, 255, 255));
        changeFieldsEmpty.setForeground(new java.awt.Color(255, 0, 51));
        changeFieldsEmpty.setText("Complete todos los campos");

        changePasswordNotMatch.setBackground(new java.awt.Color(255, 255, 255));
        changePasswordNotMatch.setForeground(new java.awt.Color(255, 0, 51));
        changePasswordNotMatch.setText("Las contraseñas no concuerdan");

        changeWrongPassword.setBackground(new java.awt.Color(255, 255, 255));
        changeWrongPassword.setForeground(new java.awt.Color(255, 0, 51));
        changeWrongPassword.setText("La contraseña es erronea");

        wrongPassword.setBackground(new java.awt.Color(255, 255, 255));
        wrongPassword.setForeground(new java.awt.Color(255, 0, 51));
        wrongPassword.setText("La contraseña es erronea");

        changeSucces.setBackground(new java.awt.Color(255, 255, 255));
        changeSucces.setForeground(new java.awt.Color(0, 153, 0));
        changeSucces.setText("Contraseña cambiada ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(pictureLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(username, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(231, 231, 231)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(60, 60, 60)
                                        .addComponent(changePasswordBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(actualPasswordLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(actualPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(actualPasswordSeparator, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(newPasswordLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(newPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(newPasswordSeparator, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(newRepeatLabel)
                                    .addComponent(newRepeatField, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(newRepeatSeparator, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(profilePictureBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(295, 295, 295)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(14, 14, 14)
                                        .addComponent(changeWrongPassword))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(20, 20, 20)
                                        .addComponent(changeSucces))
                                    .addComponent(changePasswordNotMatch)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(changeFieldsEmpty))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(deleteUserBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(277, 277, 277)
                                .addComponent(changeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(cancelChangeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(PasswordLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(PasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(101, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(passwordSeparator, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(repeatPasswordLabel)
                            .addComponent(repeatPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(repeatSeparator, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addComponent(fieldsEmpty))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(passwordNotMatch)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(13, 13, 13)
                                        .addComponent(wrongPassword))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(deleteBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(cancelBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(logoLalbel, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(16, 16, 16))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(pictureLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(username, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(changePasswordBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(actualPasswordLabel)
                        .addGap(6, 6, 6)
                        .addComponent(actualPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(actualPasswordSeparator, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(newPasswordLabel)
                        .addGap(6, 6, 6)
                        .addComponent(newPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(newPasswordSeparator, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(newRepeatLabel)
                        .addGap(6, 6, 6)
                        .addComponent(newRepeatField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(newRepeatSeparator, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(profilePictureBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(changeWrongPassword)
                        .addGap(6, 6, 6)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(changeSucces)
                            .addComponent(changePasswordNotMatch))
                        .addGap(6, 6, 6)
                        .addComponent(changeFieldsEmpty)))
                .addGap(2, 2, 2)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(deleteUserBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(changeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cancelChangeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(27, 27, 27)
                .addComponent(PasswordLabel)
                .addGap(10, 10, 10)
                .addComponent(PasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(passwordSeparator, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(repeatPasswordLabel)
                        .addGap(6, 6, 6)
                        .addComponent(repeatPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(repeatSeparator, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(fieldsEmpty)
                        .addGap(2, 2, 2)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addComponent(passwordNotMatch))
                            .addComponent(wrongPassword))
                        .addGap(12, 12, 12)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(deleteBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cancelBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(logoLalbel, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void profilePictureBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_profilePictureBtnMouseClicked
        JFileChooser fileChooser = new JFileChooser();
        FileNameExtensionFilter filter = new FileNameExtensionFilter("JPG & PNG", "JPG", "PNG");
        fileChooser.setFileFilter(filter);
        fileChooser.setDialogTitle("Buscar imagen de perfil");
        int result = fileChooser.showOpenDialog(this);
        if(result == JFileChooser.APPROVE_OPTION){
            String archivo = fileChooser.getSelectedFile().getAbsolutePath();
            ImageIcon profilePicture = new ImageIcon(archivo);
            Image profileImage = profilePicture.getImage().getScaledInstance(200,200,Image.SCALE_SMOOTH);
            ImageIcon scaledProfilePicture = new ImageIcon(profileImage);
            pictureLabel.setIcon(scaledProfilePicture);
            this.principalMenu.changePicture(archivo);
            currentUser.setImage(archivo);
            logicController.editUser(currentUser);
            
        }
    }//GEN-LAST:event_profilePictureBtnMouseClicked

    private void deleteUserBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteUserBtnMouseClicked
        deleteBtn.setVisible(true);
        cancelBtn.setVisible(true);
        repeatSeparator.setVisible(true);
        PasswordLabel.setVisible(true);
        PasswordField.setVisible(true);
        passwordSeparator.setVisible(true);
        repeatPasswordField.setVisible(true);
        repeatPasswordLabel.setVisible(true);
        fieldsEmpty.setVisible(false);
         passwordNotMatch.setVisible(false);
    }//GEN-LAST:event_deleteUserBtnMouseClicked

    private void PasswordFieldMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PasswordFieldMousePressed
        if(String.valueOf(PasswordField.getPassword()).equals("********")){
            PasswordField.setText("");
            PasswordField.setForeground(Color.black);
        }

        

        if(String.valueOf(repeatPasswordField.getPassword()).isEmpty()){
            repeatPasswordField.setText("********");
            repeatPasswordField.setForeground(new Color(204,204,204));
        }

        passwordNotMatch.setVisible(false);
        fieldsEmpty.setVisible(false);
        wrongPassword.setVisible(false);
        
    }//GEN-LAST:event_PasswordFieldMousePressed

    private void repeatPasswordFieldMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_repeatPasswordFieldMousePressed
        if(String.valueOf(repeatPasswordField.getPassword()).equals("********")){
            repeatPasswordField.setText("");
            repeatPasswordField.setForeground(Color.black);
        }

        

        if(String.valueOf(PasswordField.getPassword()).isEmpty()){
            PasswordField.setText("********");
            PasswordField.setForeground(new Color(204,204,204));
        }

        passwordNotMatch.setVisible(false);
        fieldsEmpty.setVisible(false);
        wrongPassword.setVisible(false);
        
    }//GEN-LAST:event_repeatPasswordFieldMousePressed

    private void deleteBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteBtnMouseClicked
        String password = String.valueOf(PasswordField.getPassword());
        String repeat = String.valueOf(repeatPasswordField.getPassword());
        if(password.equals("********") || repeat.equals("********")){
            fieldsEmpty.setVisible(true);
        }
        else if(password.equals(currentUser.getPassword())){
            if(password.equals(repeat)){
                int optionSelected = JOptionPane.showInternalConfirmDialog(null, "Esta seguro que desea borrar el usuario?", "Eliminar Usuario", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);
                if(optionSelected == 0){
                    logicController.deleteUser(currentUser.getUsername());
                    principalMenu.exitToLogin();
                }
                
            }
            else{
                passwordNotMatch.setVisible(true);

            }
        }
        else{
            wrongPassword.setVisible(true);
        }
    }//GEN-LAST:event_deleteBtnMouseClicked

    private void cancelBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelBtnMouseClicked
        restartDeleteUser();
    }//GEN-LAST:event_cancelBtnMouseClicked

    private void deleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_deleteBtnActionPerformed

    private void changePasswordBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_changePasswordBtnMouseClicked
        actualPasswordField.setVisible(true);
        actualPasswordLabel.setVisible(true);
        actualPasswordSeparator.setVisible(true);
        newPasswordField.setVisible(true);
        newPasswordLabel.setVisible(true);
        newPasswordSeparator.setVisible(true);
        newRepeatField.setVisible(true);
        newRepeatLabel.setVisible(true);
        newRepeatSeparator.setVisible(true);
        changeBtn.setVisible(true);
        cancelChangeBtn.setVisible(true);
    }//GEN-LAST:event_changePasswordBtnMouseClicked

    private void actualPasswordFieldMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_actualPasswordFieldMousePressed
        if(String.valueOf(actualPasswordField.getPassword()).equals("********")){
            actualPasswordField.setText("");
            actualPasswordField.setForeground(Color.black);
        }
        
        if(String.valueOf(newPasswordField.getPassword()).isEmpty()){
            newPasswordField.setText("********");
            newPasswordField.setForeground(new Color(204,204,204));
        }
        
        if(String.valueOf(newRepeatField.getPassword()).isEmpty()){
            newRepeatField.setText("********");
            newRepeatField.setForeground(new Color(204,204,204));
        }
        
        changePasswordNotMatch.setVisible(false);
        changeWrongPassword.setVisible(false);
        changeFieldsEmpty.setVisible(false);
        changeSucces.setVisible(false);
    }//GEN-LAST:event_actualPasswordFieldMousePressed

    private void newPasswordFieldMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_newPasswordFieldMousePressed
        if(String.valueOf(newPasswordField.getPassword()).equals("********")){
            newPasswordField.setText("");
            newPasswordField.setForeground(Color.black);
        }
        
        if(String.valueOf(actualPasswordField.getPassword()).isEmpty()){
            actualPasswordField.setText("********");
            actualPasswordField.setForeground(new Color(204,204,204));
        }
        
        if(String.valueOf(newRepeatField.getPassword()).isEmpty()){
            newRepeatField.setText("********");
            newRepeatField.setForeground(new Color(204,204,204));
        }
        
        changePasswordNotMatch.setVisible(false);
        changeWrongPassword.setVisible(false);
        changeFieldsEmpty.setVisible(false);
        changeSucces.setVisible(false);
    }//GEN-LAST:event_newPasswordFieldMousePressed

    private void newRepeatFieldMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_newRepeatFieldMousePressed
        if(String.valueOf(newRepeatField.getPassword()).equals("********")){
            newRepeatField.setText("");
            newRepeatField.setForeground(Color.black);
        }
        
        if(String.valueOf(actualPasswordField.getPassword()).isEmpty()){
            actualPasswordField.setText("********");
            actualPasswordField.setForeground(new Color(204,204,204));
        }
        
        if(String.valueOf(newPasswordField.getPassword()).isEmpty()){
            newPasswordField.setText("********");
            newPasswordField.setForeground(new Color(204,204,204));
        }
        
        changePasswordNotMatch.setVisible(false);
        changeWrongPassword.setVisible(false);
        changeFieldsEmpty.setVisible(false);
        changeSucces.setVisible(false);
    }//GEN-LAST:event_newRepeatFieldMousePressed

    private void changeBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_changeBtnMouseClicked
        String oldPassword = String.valueOf(actualPasswordField.getPassword());
        String password = String.valueOf(newPasswordField.getPassword());
        String repeat = String.valueOf(newRepeatField.getPassword());
        if(oldPassword.equals("********") || password.equals("********") || repeat.equals("********")){
            changeFieldsEmpty.setVisible(true);
        }
        else if(oldPassword.equals(currentUser.getPassword())){
            if(password.equals(repeat)){
                currentUser.setPassword(password);
                logicController.editUser(currentUser);
                restartChangePasswordWithoutLabels();
                changeSucces.setVisible(true);
                
            }
            else{
                changePasswordNotMatch.setVisible(true);

            }
        }
        else{
            changeWrongPassword.setVisible(true);
        }
    }//GEN-LAST:event_changeBtnMouseClicked

    private void changeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changeBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_changeBtnActionPerformed

    private void cancelChangeBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelChangeBtnMouseClicked
        restartChangePassword();
    }//GEN-LAST:event_cancelChangeBtnMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField PasswordField;
    private javax.swing.JLabel PasswordLabel;
    private javax.swing.JPasswordField actualPasswordField;
    private javax.swing.JLabel actualPasswordLabel;
    private javax.swing.JSeparator actualPasswordSeparator;
    private javax.swing.JButton cancelBtn;
    private javax.swing.JButton cancelChangeBtn;
    private javax.swing.JButton changeBtn;
    private javax.swing.JLabel changeFieldsEmpty;
    private javax.swing.JButton changePasswordBtn;
    private javax.swing.JLabel changePasswordNotMatch;
    private javax.swing.JLabel changeSucces;
    private javax.swing.JLabel changeWrongPassword;
    private javax.swing.JButton deleteBtn;
    private javax.swing.JButton deleteUserBtn;
    private javax.swing.JLabel fieldsEmpty;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel logoLalbel;
    private javax.swing.JPasswordField newPasswordField;
    private javax.swing.JLabel newPasswordLabel;
    private javax.swing.JSeparator newPasswordSeparator;
    private javax.swing.JPasswordField newRepeatField;
    private javax.swing.JLabel newRepeatLabel;
    private javax.swing.JSeparator newRepeatSeparator;
    private javax.swing.JLabel passwordNotMatch;
    private javax.swing.JSeparator passwordSeparator;
    private javax.swing.JLabel pictureLabel;
    private javax.swing.JButton profilePictureBtn;
    private javax.swing.JPasswordField repeatPasswordField;
    private javax.swing.JLabel repeatPasswordLabel;
    private javax.swing.JSeparator repeatSeparator;
    private javax.swing.JLabel username;
    private javax.swing.JLabel wrongPassword;
    // End of variables declaration//GEN-END:variables
}
