
package gui;

import com.formdev.flatlaf.intellijthemes.materialthemeuilite.FlatMaterialLighterIJTheme;
import gui.views.ListsPanel;
import gui.views.ProfilePanel;
import javax.swing.*;
import java.awt.*;
import logic.*;


/**
 *
 * @author galax
 */
public class PrincipalMenu extends javax.swing.JFrame {

    LogicController logicController;
    User currentUser;
    boolean isShowingListPanel;
    ProfilePanel profilePanel;
        ListsPanel listPanel;
    public PrincipalMenu(LogicController logicController, User currentUser) {
        FlatMaterialLighterIJTheme.setup();
        isShowingListPanel = true;
        this.logicController = logicController;
        this.currentUser = currentUser;
        initComponents();
        InitStyles();
        initContent();
    }
        
        private void InitStyles(){
            
        }
        
        private void initContent(){
            
            this.setVisible(true);
            
            listPanel = new ListsPanel(this.currentUser, this.logicController);
            listPanel.setSize(776, 668);
            listPanel.setLocation(0,0);
            profilePanel = new ProfilePanel(logicController, currentUser, this);
            profilePanel.setPreferredSize(new Dimension(857,690));
            profilePanel.setLocation(0, 0);
            
            
            Username.setText(currentUser.getUsername());
            if(currentUser.existImage()){
                ImageIcon profilePicture = new ImageIcon(currentUser.getImage());
                Image profileImage = profilePicture.getImage().getScaledInstance(60,60,Image.SCALE_SMOOTH);
                ImageIcon scaledProfilePicture = new ImageIcon(profileImage);
                ProfilePicture.setIcon(scaledProfilePicture);
                jPanel1.revalidate();
                jPanel1.repaint();
            }
            this.setIconImage(new ImageIcon(this.getClass().getResource("/icons/LogoNoText.png")).getImage());
            
            PrincipalPanel.removeAll();
            PrincipalPanel.add(listPanel, BorderLayout.CENTER);
            listPanel.createAllLists();
            PrincipalPanel.revalidate();
            PrincipalPanel.repaint();
        }
        
        public void changePicture(String path){
            ImageIcon profilePicture = new ImageIcon(path);
            Image profileImage = profilePicture.getImage().getScaledInstance(60,60,Image.SCALE_SMOOTH);
            ImageIcon scaledProfilePicture = new ImageIcon(profileImage);
            ProfilePicture.setIcon(scaledProfilePicture);
            jPanel1.revalidate();
            jPanel1.repaint();
        }
        
        public void exitToLogin(){
            dispose();
            new Login(this.logicController);
        }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Background = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        Username = new javax.swing.JTextArea();
        jSeparator1 = new javax.swing.JSeparator();
        ImageIcon originalIcon = new ImageIcon(this.getClass().getResource("/icons/default_avatar.png"));
        Image image = originalIcon.getImage().getScaledInstance(60,60,Image.SCALE_SMOOTH);
        ImageIcon scaledIcon = new javax.swing.ImageIcon(image);
        ProfilePicture = new javax.swing.JLabel(scaledIcon);
        btnPerfil = new javax.swing.JButton();
        btnListas1 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        btnCerrarSesion = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        PrincipalPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("ToDoList");
        setMinimumSize(new java.awt.Dimension(258, 700));

        Background.setBackground(new java.awt.Color(246, 246, 246));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        Username.setEditable(false);
        Username.setBackground(new java.awt.Color(255, 255, 255));
        Username.setColumns(20);
        Username.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        Username.setForeground(new java.awt.Color(0, 0, 0));
        Username.setRows(5);
        Username.setText("UserName");

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));

        ProfilePicture.setBackground(new java.awt.Color(0, 0, 0));
        ProfilePicture.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        btnPerfil.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        btnPerfil.setForeground(new java.awt.Color(0, 0, 0));
        btnPerfil.setIcon(new ImageIcon(this.getClass().getResource("/icons/profile.png")));
        btnPerfil.setText("Perfil");
        btnPerfil.setBorder(new javax.swing.border.MatteBorder(null));
        btnPerfil.setBorderPainted(false);
        btnPerfil.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnPerfil.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnPerfil.setIconTextGap(10);
        btnPerfil.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPerfilMouseClicked(evt);
            }
        });

        btnListas1.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        btnListas1.setForeground(new java.awt.Color(0, 0, 0));
        btnListas1.setIcon(new javax.swing.ImageIcon(this.getClass().getResource("/icons/lista.png")));
        btnListas1.setText("Listas");
        btnListas1.setBorder(new javax.swing.border.MatteBorder(null));
        btnListas1.setBorderPainted(false);
        btnListas1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnListas1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnListas1.setIconTextGap(10);
        btnListas1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnListas1MouseClicked(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        btnCerrarSesion.setFont(new java.awt.Font("Rockwell", 1, 24)); // NOI18N
        btnCerrarSesion.setForeground(new java.awt.Color(0, 0, 0));
        btnCerrarSesion.setText("Cerrar Sesión");
        btnCerrarSesion.setBorder(null);
        btnCerrarSesion.setBorderPainted(false);
        btnCerrarSesion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCerrarSesion.setHideActionText(true);
        btnCerrarSesion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCerrarSesionMouseClicked(evt);
            }
        });
        btnCerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarSesionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnCerrarSesion, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCerrarSesion, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Rockwell", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setText("Bienvenido");

        jLabel2.setIcon(new ImageIcon(this.getClass().getResource("/icons/Logo.png")));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnPerfil, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(84, 84, 84)
                                .addComponent(jLabel1))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addComponent(ProfilePicture, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(Username, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(281, 281, 281))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnListas1, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(ProfilePicture, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(Username, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(75, 75, 75)
                .addComponent(btnListas1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnPerfil, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        PrincipalPanel.setBackground(new java.awt.Color(236, 236, 236));
        PrincipalPanel.setForeground(new java.awt.Color(255, 0, 255));
        PrincipalPanel.setPreferredSize(new java.awt.Dimension(778, 670));
        PrincipalPanel.setLayout(new javax.swing.BoxLayout(PrincipalPanel, javax.swing.BoxLayout.LINE_AXIS));

        javax.swing.GroupLayout BackgroundLayout = new javax.swing.GroupLayout(Background);
        Background.setLayout(BackgroundLayout);
        BackgroundLayout.setHorizontalGroup(
            BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BackgroundLayout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(PrincipalPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 857, Short.MAX_VALUE))
        );
        BackgroundLayout.setVerticalGroup(
            BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(BackgroundLayout.createSequentialGroup()
                .addComponent(PrincipalPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 690, Short.MAX_VALUE)
                .addGap(4, 4, 4))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarSesionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCerrarSesionActionPerformed

    private void btnCerrarSesionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCerrarSesionMouseClicked
        exitToLogin();
        
    }//GEN-LAST:event_btnCerrarSesionMouseClicked

    private void btnListas1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnListas1MouseClicked
        if(!isShowingListPanel){
            PrincipalPanel.removeAll();
            PrincipalPanel.add(listPanel, BorderLayout.CENTER);
            PrincipalPanel.revalidate();
            PrincipalPanel.repaint();
            isShowingListPanel = true;
        }
    }//GEN-LAST:event_btnListas1MouseClicked

    private void btnPerfilMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPerfilMouseClicked
        if(isShowingListPanel){
            PrincipalPanel.removeAll();
            PrincipalPanel.add(profilePanel, BorderLayout.CENTER);
            PrincipalPanel.revalidate();
            PrincipalPanel.repaint();
            isShowingListPanel = false;
        }
    }//GEN-LAST:event_btnPerfilMouseClicked

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Background;
    private javax.swing.JPanel PrincipalPanel;
    private javax.swing.JLabel ProfilePicture;
    private javax.swing.JTextArea Username;
    private javax.swing.JButton btnCerrarSesion;
    private javax.swing.JButton btnListas1;
    private javax.swing.JButton btnPerfil;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    // End of variables declaration//GEN-END:variables
}
