
package gui;

import com.formdev.flatlaf.intellijthemes.materialthemeuilite.FlatMaterialLighterIJTheme;
import java.awt.Color;
import javax.swing.ImageIcon;
import logic.LogicController;
import logic.User;

public class Login extends javax.swing.JFrame {

    LogicController logicController;
    boolean isLogin;
    boolean isRegister;
    public Login(LogicController logicController) {
        FlatMaterialLighterIJTheme.setup();
        this.logicController = logicController;
        this.setVisible(true);
        this.setLocationRelativeTo(null);
        
        
        initComponents();
        this.isLogin = true;
        this.isRegister = false;
        this.setSize(452,567);
        registerPanel.setVisible(false);
        passwordNotMatch.setVisible(false);
        exisitingUser.setVisible(false);
        userPasswordnotMatch.setVisible(false);
        userNotMatch.setVisible(false);
        fieldsEmptyLogin.setVisible(false);
        fieldsEmptyRegister.setVisible(false);
        succesLabel.setVisible(false);
        this.setIconImage(new ImageIcon(this.getClass().getResource("/icons/LogoNoText.png")).getImage());
    }
    
    private void restartLogin(){
        loginPasswordField.setText("********");
        loginPasswordField.setForeground(new Color(204,204,204));
        userTxtField.setText("Ingrese su nombre de usuario");
        userTxtField.setForeground(new Color(204,204,204));
        userPasswordnotMatch.setVisible(false);
        userNotMatch.setVisible(false);
        fieldsEmptyLogin.setVisible(false);
    }
    
    private void restartRegister(){
        registerPasswordField.setText("********");
        registerPasswordField.setForeground(new Color(204,204,204));
        repeatPasswordField.setText("********");
        repeatPasswordField.setForeground(new Color(204,204,204));
        registerUserTxtField.setText("Ingrese su nombre de usuario");
        registerUserTxtField.setForeground(new Color(204,204,204));
        passwordNotMatch.setVisible(false);
        exisitingUser.setVisible(false);
        fieldsEmptyRegister.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        registerPanel = new javax.swing.JPanel();
        registerUserLabel = new javax.swing.JLabel();
        registerUserSeparator = new javax.swing.JSeparator();
        registerUserTxtField = new javax.swing.JTextField();
        registerPaswordSeparator = new javax.swing.JSeparator();
        registerPasswordLabel = new javax.swing.JLabel();
        registerPasswordField = new javax.swing.JPasswordField();
        btnRegister = new javax.swing.JButton();
        repeatPasswordSeparator = new javax.swing.JSeparator();
        repeatPasswordLabel = new javax.swing.JLabel();
        repeatPasswordField = new javax.swing.JPasswordField();
        exisitingUser = new javax.swing.JLabel();
        passwordNotMatch = new javax.swing.JLabel();
        fieldsEmptyRegister = new javax.swing.JLabel();
        succesLabel = new javax.swing.JLabel();
        loginPanel = new javax.swing.JPanel();
        userLabel = new javax.swing.JLabel();
        userSeparator = new javax.swing.JSeparator();
        userTxtField = new javax.swing.JTextField();
        passwordLabel = new javax.swing.JLabel();
        passwordSeparator = new javax.swing.JSeparator();
        btnLogin = new javax.swing.JButton();
        loginPasswordField = new javax.swing.JPasswordField();
        userPasswordnotMatch = new javax.swing.JLabel();
        userNotMatch = new javax.swing.JLabel();
        fieldsEmptyLogin = new javax.swing.JLabel();
        btnLoginOptn = new javax.swing.JButton();
        btnRegisterOptn = new javax.swing.JButton();
        logo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("ToDoList: Login");
        setResizable(false);

        jPanel1.setPreferredSize(new java.awt.Dimension(427, 567));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        registerPanel.setBackground(new java.awt.Color(255, 255, 255));

        registerUserLabel.setBackground(new java.awt.Color(255, 255, 255));
        registerUserLabel.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        registerUserLabel.setForeground(new java.awt.Color(0, 0, 0));
        registerUserLabel.setText("Ingrese el nuevo usuario");

        registerUserTxtField.setBackground(new java.awt.Color(255, 255, 255));
        registerUserTxtField.setForeground(new java.awt.Color(204, 204, 204));
        registerUserTxtField.setText("Ingrese su nombre de usuario");
        registerUserTxtField.setBorder(null);
        registerUserTxtField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                registerUserTxtFieldMousePressed(evt);
            }
        });
        registerUserTxtField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerUserTxtFieldActionPerformed(evt);
            }
        });

        registerPasswordLabel.setBackground(new java.awt.Color(255, 255, 255));
        registerPasswordLabel.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        registerPasswordLabel.setForeground(new java.awt.Color(0, 0, 0));
        registerPasswordLabel.setText("Ingrese la nueva Contraseña");

        registerPasswordField.setBackground(new java.awt.Color(255, 255, 255));
        registerPasswordField.setForeground(new java.awt.Color(204, 204, 204));
        registerPasswordField.setText("********");
        registerPasswordField.setBorder(null);
        registerPasswordField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                registerPasswordFieldMousePressed(evt);
            }
        });

        btnRegister.setFont(new java.awt.Font("Rockwell", 1, 24)); // NOI18N
        btnRegister.setForeground(new java.awt.Color(0, 0, 0));
        btnRegister.setText("Registrarse");
        btnRegister.setBorder(null);
        btnRegister.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRegister.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRegisterMouseClicked(evt);
            }
        });

        repeatPasswordLabel.setBackground(new java.awt.Color(255, 255, 255));
        repeatPasswordLabel.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        repeatPasswordLabel.setForeground(new java.awt.Color(0, 0, 0));
        repeatPasswordLabel.setText("Ingrese nuevamente la contraseña");

        repeatPasswordField.setBackground(new java.awt.Color(255, 255, 255));
        repeatPasswordField.setForeground(new java.awt.Color(204, 204, 204));
        repeatPasswordField.setText("********");
        repeatPasswordField.setBorder(null);
        repeatPasswordField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                repeatPasswordFieldMousePressed(evt);
            }
        });

        exisitingUser.setBackground(new java.awt.Color(255, 255, 255));
        exisitingUser.setForeground(new java.awt.Color(255, 0, 51));
        exisitingUser.setText("El Usuario ya existe, pruebe con otro ");

        passwordNotMatch.setBackground(new java.awt.Color(255, 255, 255));
        passwordNotMatch.setForeground(new java.awt.Color(255, 0, 51));
        passwordNotMatch.setText("Las contraseñas no concuerdan");

        fieldsEmptyRegister.setBackground(new java.awt.Color(255, 255, 255));
        fieldsEmptyRegister.setForeground(new java.awt.Color(255, 0, 51));
        fieldsEmptyRegister.setText("Complete todos los campos");

        succesLabel.setBackground(new java.awt.Color(255, 255, 255));
        succesLabel.setForeground(new java.awt.Color(0, 204, 51));
        succesLabel.setText("Usuario creado exitosamente");

        javax.swing.GroupLayout registerPanelLayout = new javax.swing.GroupLayout(registerPanel);
        registerPanel.setLayout(registerPanelLayout);
        registerPanelLayout.setHorizontalGroup(
            registerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(registerPanelLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(registerUserTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(registerPanelLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(registerUserSeparator, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(registerPanelLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(registerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(registerPaswordSeparator, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(registerPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGroup(registerPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(registerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(repeatPasswordSeparator, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(registerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(repeatPasswordLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(repeatPasswordField, javax.swing.GroupLayout.Alignment.LEADING))))
            .addGroup(registerPanelLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(registerUserLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, registerPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnRegister, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46))
            .addGroup(registerPanelLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(registerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(registerPasswordLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, registerPanelLayout.createSequentialGroup()
                        .addComponent(exisitingUser)
                        .addGap(9, 9, 9))))
            .addGroup(registerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, registerPanelLayout.createSequentialGroup()
                    .addContainerGap(87, Short.MAX_VALUE)
                    .addComponent(passwordNotMatch)
                    .addGap(81, 81, 81)))
            .addGroup(registerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(registerPanelLayout.createSequentialGroup()
                    .addGap(93, 93, 93)
                    .addComponent(fieldsEmptyRegister)
                    .addContainerGap(93, Short.MAX_VALUE)))
            .addGroup(registerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, registerPanelLayout.createSequentialGroup()
                    .addContainerGap(86, Short.MAX_VALUE)
                    .addComponent(succesLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(71, 71, 71)))
        );
        registerPanelLayout.setVerticalGroup(
            registerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(registerPanelLayout.createSequentialGroup()
                .addComponent(registerUserLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(registerUserTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(registerUserSeparator, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(exisitingUser, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(registerPasswordLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addGroup(registerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(registerPanelLayout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(registerPaswordSeparator, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(registerPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(repeatPasswordLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addGroup(registerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(registerPanelLayout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(repeatPasswordSeparator, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(repeatPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addComponent(btnRegister, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(registerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(registerPanelLayout.createSequentialGroup()
                    .addGap(282, 282, 282)
                    .addComponent(passwordNotMatch, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(103, Short.MAX_VALUE)))
            .addGroup(registerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(registerPanelLayout.createSequentialGroup()
                    .addGap(293, 293, 293)
                    .addComponent(fieldsEmptyRegister)
                    .addContainerGap(100, Short.MAX_VALUE)))
            .addGroup(registerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, registerPanelLayout.createSequentialGroup()
                    .addContainerGap(279, Short.MAX_VALUE)
                    .addComponent(succesLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(103, 103, 103)))
        );

        loginPanel.setBackground(new java.awt.Color(255, 255, 255));
        loginPanel.setOpaque(false);

        userLabel.setBackground(new java.awt.Color(255, 255, 255));
        userLabel.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        userLabel.setForeground(new java.awt.Color(0, 0, 0));
        userLabel.setText("Usuario");

        userTxtField.setBackground(new java.awt.Color(255, 255, 255));
        userTxtField.setForeground(new java.awt.Color(204, 204, 204));
        userTxtField.setText("Ingrese su nombre de usuario");
        userTxtField.setBorder(null);
        userTxtField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                userTxtFieldMousePressed(evt);
            }
        });
        userTxtField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userTxtFieldActionPerformed(evt);
            }
        });

        passwordLabel.setBackground(new java.awt.Color(255, 255, 255));
        passwordLabel.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        passwordLabel.setForeground(new java.awt.Color(0, 0, 0));
        passwordLabel.setText("Contraseña");

        btnLogin.setFont(new java.awt.Font("Rockwell", 1, 24)); // NOI18N
        btnLogin.setForeground(new java.awt.Color(0, 0, 0));
        btnLogin.setText("Iniciar Sesión");
        btnLogin.setBorder(null);
        btnLogin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLoginMouseClicked(evt);
            }
        });

        loginPasswordField.setBackground(new java.awt.Color(255, 255, 255));
        loginPasswordField.setForeground(new java.awt.Color(204, 204, 204));
        loginPasswordField.setText("********");
        loginPasswordField.setBorder(null);
        loginPasswordField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                loginPasswordFieldMousePressed(evt);
            }
        });

        userPasswordnotMatch.setBackground(new java.awt.Color(255, 255, 255));
        userPasswordnotMatch.setForeground(new java.awt.Color(255, 0, 51));
        userPasswordnotMatch.setText("El usuario y/o contraseña son incorrectos");

        userNotMatch.setBackground(new java.awt.Color(255, 255, 255));
        userNotMatch.setForeground(new java.awt.Color(255, 0, 51));
        userNotMatch.setText("El usuario no existe");

        fieldsEmptyLogin.setBackground(new java.awt.Color(255, 255, 255));
        fieldsEmptyLogin.setForeground(new java.awt.Color(255, 0, 51));
        fieldsEmptyLogin.setText("Complete todos los campos");

        javax.swing.GroupLayout loginPanelLayout = new javax.swing.GroupLayout(loginPanel);
        loginPanel.setLayout(loginPanelLayout);
        loginPanelLayout.setHorizontalGroup(
            loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginPanelLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(userLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(loginPanelLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(userTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(loginPanelLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(userSeparator, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(loginPanelLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(passwordLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(loginPanelLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(passwordSeparator, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(loginPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGroup(loginPanelLayout.createSequentialGroup()
                .addGap(115, 115, 115)
                .addComponent(userNotMatch))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, loginPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(userPasswordnotMatch)
                    .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, loginPanelLayout.createSequentialGroup()
                            .addComponent(fieldsEmptyLogin)
                            .addGap(86, 86, 86))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, loginPanelLayout.createSequentialGroup()
                            .addComponent(btnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(49, 49, 49)))))
        );
        loginPanelLayout.setVerticalGroup(
            loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginPanelLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(userLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(userTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(userSeparator, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(userNotMatch, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14)
                .addComponent(passwordLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(loginPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(passwordSeparator, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(userPasswordnotMatch, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fieldsEmptyLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19)
                .addComponent(btnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnLoginOptn.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        btnLoginOptn.setForeground(new java.awt.Color(0, 0, 0));
        btnLoginOptn.setText("Login");
        btnLoginOptn.setBorder(null);
        btnLoginOptn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLoginOptnMouseClicked(evt);
            }
        });

        btnRegisterOptn.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        btnRegisterOptn.setForeground(new java.awt.Color(0, 0, 0));
        btnRegisterOptn.setText("Registrarse");
        btnRegisterOptn.setBorder(null);
        btnRegisterOptn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRegisterOptnMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(registerPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(loginPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(102, 102, 102)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(logo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btnLoginOptn, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(btnRegisterOptn, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(logo, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnLoginOptn, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRegisterOptn, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(registerPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(loginPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void userTxtFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userTxtFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userTxtFieldActionPerformed

    private void registerUserTxtFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerUserTxtFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_registerUserTxtFieldActionPerformed

    private void btnLoginOptnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLoginOptnMouseClicked
        if(!isLogin){
            isLogin = true;
            isRegister = false;
            loginPanel.setVisible(true);
            registerPanel.setVisible(false);
            restartRegister();
        }
    }//GEN-LAST:event_btnLoginOptnMouseClicked

    private void btnRegisterOptnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegisterOptnMouseClicked
        if(!isRegister){
            isRegister = false;
            isLogin = false;
            loginPanel.setVisible(false);
            registerPanel.setVisible(true);
            restartLogin();
            
        }
    }//GEN-LAST:event_btnRegisterOptnMouseClicked

    private void userTxtFieldMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userTxtFieldMousePressed
        if(userTxtField.getText().equals("Ingrese su nombre de usuario")){
            userTxtField.setText("");
            userTxtField.setForeground(Color.black);
            
        }
        if(String.valueOf(loginPasswordField.getPassword()).isEmpty()){
            loginPasswordField.setText("********");
            loginPasswordField.setForeground(new Color(204,204,204));
        }
        
        userPasswordnotMatch.setVisible(false);
        userNotMatch.setVisible(false);
        fieldsEmptyLogin.setVisible(false);
    }//GEN-LAST:event_userTxtFieldMousePressed

    private void loginPasswordFieldMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginPasswordFieldMousePressed
        if(String.valueOf(loginPasswordField.getPassword()).equals("********")){
            loginPasswordField.setText("");
            loginPasswordField.setForeground(Color.black);
        }
        
        if(userTxtField.getText().isEmpty()){
            userTxtField.setText("Ingrese su nombre de usuario");
            userTxtField.setForeground(new Color(204,204,204));
        }
        
        userPasswordnotMatch.setVisible(false);
        userNotMatch.setVisible(false);
        fieldsEmptyLogin.setVisible(false);
    }//GEN-LAST:event_loginPasswordFieldMousePressed

    private void registerUserTxtFieldMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registerUserTxtFieldMousePressed
        if(registerUserTxtField.getText().equals("Ingrese su nombre de usuario")){
            registerUserTxtField.setText("");
            registerUserTxtField.setForeground(Color.black);
            
            
        }
        if(String.valueOf(registerPasswordField.getPassword()).isEmpty()){
            registerPasswordField.setText("********");
            registerPasswordField.setForeground(new Color(204,204,204));
        }
        
        if(String.valueOf(repeatPasswordField.getPassword()).isEmpty()){
            repeatPasswordField.setText("********");
            repeatPasswordField.setForeground(new Color(204,204,204));
        }
        
        exisitingUser.setVisible(false);
        fieldsEmptyRegister.setVisible(false);
        succesLabel.setVisible(false);
    }//GEN-LAST:event_registerUserTxtFieldMousePressed

    private void registerPasswordFieldMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registerPasswordFieldMousePressed
        if(String.valueOf(registerPasswordField.getPassword()).equals("********")){
            registerPasswordField.setText("");
            registerPasswordField.setForeground(Color.black);
        }
        
        if(registerUserTxtField.getText().isEmpty()){
            registerUserTxtField.setText("Ingrese su nombre de usuario");
            registerUserTxtField.setForeground(new Color(204,204,204));
        }
        
        if(String.valueOf(repeatPasswordField.getPassword()).isEmpty()){
            repeatPasswordField.setText("********");
            repeatPasswordField.setForeground(new Color(204,204,204));
        }
        
        passwordNotMatch.setVisible(false);
        fieldsEmptyRegister.setVisible(false);
        succesLabel.setVisible(false);
    }//GEN-LAST:event_registerPasswordFieldMousePressed

    private void repeatPasswordFieldMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_repeatPasswordFieldMousePressed
        if(String.valueOf(repeatPasswordField.getPassword()).equals("********")){
            repeatPasswordField.setText("");
            repeatPasswordField.setForeground(Color.black);
        }
        
        if(registerUserTxtField.getText().isEmpty()){
            registerUserTxtField.setText("Ingrese su nombre de usuario");
            registerUserTxtField.setForeground(new Color(204,204,204));
        }
        
        if(String.valueOf(registerPasswordField.getPassword()).isEmpty()){
            registerPasswordField.setText("********");
            registerPasswordField.setForeground(new Color(204,204,204));
        }
        
        passwordNotMatch.setVisible(false);
        fieldsEmptyRegister.setVisible(false);
        succesLabel.setVisible(false);
    }//GEN-LAST:event_repeatPasswordFieldMousePressed

    private void btnLoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLoginMouseClicked
        String username = userTxtField.getText();
        String password = String.valueOf(loginPasswordField.getPassword());
        if(username.equals("Ingrese su nombre de usuario") || password.equals("********")){
            userTxtField.setText("Ingrese su nombre de usuario");
            userTxtField.setForeground(new Color(204,204,204));
            loginPasswordField.setText("********");
            loginPasswordField.setForeground(new Color(204,204,204));
            fieldsEmptyLogin.setVisible(true);
        }
        else{
            User user = this.logicController.findUser(username);
            if(user != null){
                if(user.getPassword().equals(password)){
                    dispose();
                    new PrincipalMenu(this.logicController, user);
                }
                else{
                    userTxtField.setText("Ingrese su nombre de usuario");
                    userTxtField.setForeground(new Color(204,204,204));
                    loginPasswordField.setText("********");
                    loginPasswordField.setForeground(new Color(204,204,204));
                    userPasswordnotMatch.setVisible(true);
                }
            }
            else{
                userTxtField.setText("Ingrese su nombre de usuario");
                userTxtField.setForeground(new Color(204,204,204));
                loginPasswordField.setText("********");
                loginPasswordField.setForeground(new Color(204,204,204));
                userNotMatch.setVisible(true);
            }
        }
        
        
       
       
    }//GEN-LAST:event_btnLoginMouseClicked

    private void btnRegisterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegisterMouseClicked
        String username = registerUserTxtField.getText();
        String password = String.valueOf(registerPasswordField.getPassword());
        String repeat = String.valueOf(repeatPasswordField.getPassword());
        if(username.equals("Ingrese su nombre de usuario") || password.equals("********") || repeat.equals("********")){
            fieldsEmptyRegister.setVisible(true);
        }
        else{
            if(password.equals(repeat)){
                if(!logicController.createUser(username, password)){
                    exisitingUser.setVisible(true);
                }
                else{
                    restartRegister();
                    succesLabel.setVisible(true);
                }
            }
            else{
                passwordNotMatch.setVisible(true);

            }
        }
        
    }//GEN-LAST:event_btnRegisterMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogin;
    private javax.swing.JButton btnLoginOptn;
    private javax.swing.JButton btnRegister;
    private javax.swing.JButton btnRegisterOptn;
    private javax.swing.JLabel exisitingUser;
    private javax.swing.JLabel fieldsEmptyLogin;
    private javax.swing.JLabel fieldsEmptyRegister;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel loginPanel;
    private javax.swing.JPasswordField loginPasswordField;
    private javax.swing.JLabel logo;
    private javax.swing.JLabel passwordLabel;
    private javax.swing.JLabel passwordNotMatch;
    private javax.swing.JSeparator passwordSeparator;
    private javax.swing.JPanel registerPanel;
    private javax.swing.JPasswordField registerPasswordField;
    private javax.swing.JLabel registerPasswordLabel;
    private javax.swing.JSeparator registerPaswordSeparator;
    private javax.swing.JLabel registerUserLabel;
    private javax.swing.JSeparator registerUserSeparator;
    private javax.swing.JTextField registerUserTxtField;
    private javax.swing.JPasswordField repeatPasswordField;
    private javax.swing.JLabel repeatPasswordLabel;
    private javax.swing.JSeparator repeatPasswordSeparator;
    private javax.swing.JLabel succesLabel;
    private javax.swing.JLabel userLabel;
    private javax.swing.JLabel userNotMatch;
    private javax.swing.JLabel userPasswordnotMatch;
    private javax.swing.JSeparator userSeparator;
    private javax.swing.JTextField userTxtField;
    // End of variables declaration//GEN-END:variables
}
